[project]
name = "llmexperiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.13.2",
]

[tool.uv.workspace]
members = [
]

[dependency-groups]
dev = [
    "ruff>=0.14.10",
]
